### ISSUE TITLE
Unable  to run  code 

### ISSUE THREAD

**Issue by daleepkbizsoft** [the-codepunker/audio-sync-with-text#1]
Please  provide a full sample  example  to run  tthis project

**Comment by the-codepunker** [comment]
Hi @daleepkbizsoft ,

You can see it running in the demo section here: https://www.codepunker.com/blog/sync-audio-with-text-using-javascript

Did you need something else ?

It is also implemented on other websites: https://www.leonardoenglish.com/podcasts/meet-the-english-for-curious-minds-podcast
