### ISSUE TITLE
The data type of start and end time

### ISSUE THREAD

**Issue by litingzhou1** [the-codepunker/audio-sync-with-text#2]
Hi @the-codepunker,

Thanks for sharing your work.

I saw your shared code in this link: https://www.codepunker.com/blog/sync-audio-with-text-using-javascript. Could you please tell me what is the data type of _end_ and _start_. ` { "end": "0.225","start": "0.125","text": "There" }, {"end": "0.485","start": "0.225","text": "were" }`

in transcription file, It should be time (00:00:02.330). 

Thanks!
Liting

**Comment by the-codepunker** [comment]
Hi,

That's a JavaScript array of objects. It's actually like this:

```
    [
        { "end": "0.225","start": "0.125","text": "There" },
        {"end": "0.485","start": "0.225","text": "were" },
    ]
```

Thanks,

**Comment by Turismoenjupiter** [comment]
hey, sorry for my silly question.. but how can when the audio hits over 1 minute? the code follow my text  from start to 59 secs beacause i don't know how to write the time after that. 

gelp please!

**Comment by the-codepunker** [comment]
It should work with 60... but I need to see the context in which you're using it.
